name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      # TODO: Remove --force when support for TS 4.6 is stable
      - run: npm install --force
      - run: npm run build
      - run: npm run test
      - run: npm run lint

